Medsk8/Medsk8/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("skateboardBlog.urls")),
    path('accounts/', include("accounts.urls")),
    path('learn/', include("learnSkateboard.urls")),
]

Medsk8/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('register/', views.register, name = "register"),
    path('login/', views.login_user, name = "login")
] 

Medsk8/learnSkateboard/urls.py
from django.urls import path
from . import views


app_name = "learnSkateboard"


urlpatterns = [
    path('', views.home, name = "home"),
    path('components/', views.components, name = "components"),
    
] 

Medsk8/skateboardBlog/urls.py
from django.urls import path
from . import views

app_name = "skateboardBlog"

urlpatterns = [
    path('', views.home, name = "home"),
    path('add/post/', views.add_post, name = "add_post"),
    path('view/post/', views.list_posts, name = "list_post"),
    
] 

Medsk8/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    city_choises = models.TextChoices("city", ["Riyadh", "Jeddah", "Dammam", "Medina"])
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key=True)
    avatar = models.ImageField(upload_to="images/")
    city  = models.CharField(max_length=64, choices = city_choises.choices, default=city_choises.Riyadh)
    gender = models.TextField()
    age = models.IntegerField()
    is_skater = models.BooleanField()
    phoneNumber = models.IntegerField()

Medsk8/learnSkateboard/models.py
from django.db import models

# Create your models here.

Medsk8/skateboardBlog/models.py
from django.db import models
from accounts.models import Profile

# Create your models here.

class Post(models.Model):

    post_type_choices = models.TextChoices("Post Type", ["Article", "Opinion", "Review"])
    
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=1024)
    content = models.TextField()
    publish_date = models.DateTimeField()
    image = models.ImageField(upload_to="images/")

    def __str__(self) -> str:
        return f"{self.title}, {self.publish_date}"


class Comment(models.Model):

    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    name = models.CharField(max_length=256)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)

Medsk8/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from skateboardBlog import urls
# Create your views here.

def register(request:HttpRequest):
    if request.method == "POST":

        new_user = User.objects.create_user(username=request.POST["email"], email= request.POST["email"], first_name=request.POST["first_name"], last_name=request.POST["last_name"], password=request.POST["password"])
        new_profile = Profile(user = new_user, avatar = request.FILES["avatar"], city= request.POST["city"], gender = request.POST["gender"], age = request.POST["age"], is_skater = request.POST["is_skater"], phoneNumber = request.POST["phoneNumber"])
        new_user.save()
        new_profile.save()

    return render(request, 'accounts/register.html')


def login_user(request:HttpRequest):
    msg = ""
    if request.method == "POST":
        user = authenticate(request, username=request.POST["username"], password=request.POST["password"])
        
        if user:
            login(request, user)
            return redirect("skateboardBlog:home")
        else:
            msg = "User Not Found , check your credentials"

    return render(request, "accounts/login.html", {"msg" : msg})
    

Medsk8/learnSkateboard/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

# Create your views here.


def home(request:HttpRequest):
    return render(request, "learnSkateboard/base.html")


def components(request:HttpRequest):
    return render(request, "learnSkateboard/components.html")

Medsk8/skateboardBlog/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from .models import Post
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.


def home(request:HttpRequest):
    return render(request , "skateboardBlog/home.html")



def list_posts(request: HttpRequest):
    if "search" in request.GET:
        posts = Post.objects.filter(title__contains=request.GET["search"])
    else:
        posts = Post.objects.all()

    
    #posts = Post.objects.all().order_by("-publish_date") #to order by date
    #posts = Post.objects.filter(is_published=False) #to filter by exact
    #posts = Post.objects.filter(title__contains = "aims") #to filter using postfix __contains
    return render(request, "skateboardBlog/view_posts.html", {"posts" : posts})


@login_required(login_url="/accounts/login")
def add_post(request : HttpRequest):
  
    if request.method == "POST":
        new_post = Post(title=request.POST["title"], content = request.POST["content"], publish_date=request.POST["publish_date"], post_type=request.POST["post_type"] , image=request.FILES["image"])
        new_post.save()
        return render(request , "skateboardBlog/add_post.html")
    return render(request , "skateboardBlog/add_post.html", {"Post" : Post})

def register(request:HttpRequest):
    return render(request, "accounts/register.html")


def login(request:HttpRequest):
    return render(request, "accounts/login.html")

Medsk8/accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!--Head-->
 <head>
    <meta charset= "UTF-8">
    <meta http-equiv= "X-UA-Compatible" content= "IE=edge">
    <meta name= "viewport" content= "width-device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    {% block title %}<title>Accounts</title>{% endblock %}
    
 </head>

 <body style ="background-color: #A0E4CB;">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <div class="navbar navbar-expand-md bg-dark navbar-dark text-white">
        <div class="container">
            <a href="{% url 'skateboardBlog:home' %}" class= "navbar-brand">MEDSK8</a>
            <button
                class= "navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#mainmenu"
            >
            <span class= "navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="mainmenu">
                <ul class= "navbar-nav ms-auto">
                    <li class= "nav-item"><a href="{% url 'skateboardBlog:home' %}" class="nav-link">Home</a></li>
                    <li class= "nav-item"><a href="{% url 'skateboardBlog:home' %}" class= "nav-link">Blog</a></li>
                    <li class= "nav-item"><a href="{% url 'skateboardBlog:home' %}" class="nav-link">LearnSkateboarding</a></li>
                </ul>
            </div>
        </div>
    </div>

    {% block content %}{% endblock  %}


   


</body>

Medsk8/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}

{% block title %}<title>Login</title>{% endblock %}
<section class="vh-100">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">
              <div class="col-md-6 col-lg-5 d-none d-md-block">
                <img src="{% static 'images/undraw_skateboard.svg' %}"
                  alt="login form" class="img-fluid p-4 mt-5 mx-5" style="border-radius: 1rem 0 0 1rem;" />
              </div>
              <div class="col-md-6 col-lg-7 d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">
  
                  <form method = "POST">
                    {% csrf_token %}
                    <div class="d-flex align-items-center mb-3 pb-1">
                      <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                      <span class="h1 fw-bold mb-0">MEDSK8</span>
                    </div>
  
                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>
  
                    <div class="form-outline mb-4">
                      <input type="email" id="form2Example17" class="form-control form-control-lg" name = "username"/>
                      <label class="form-label" for="form2Example17">Email address</label>
                    </div>
  
                    <div class="form-outline mb-4">
                      <input type="password" id="form2Example27" class="form-control form-control-lg" name = "password" />
                      <label class="form-label" for="form2Example27">Password</label>
                    </div>
  
                    <div class="pt-1 mb-4">
                      <button class="btn btn-dark btn-lg btn-block" type="submit">Login</button>
                    </div>
  
                    <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="{% url 'accounts:register' %}"
                        style="color: #393f81;">Register here</a></p>
                    <a href="#!" class="small text-muted">Terms of use.</a>
                    <a href="#!" class="small text-muted">Privacy policy</a>
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


{% endblock %}

Medsk8/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% block title %}<title>Register</title>{% endblock %}
{% block content %}
<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col-12 col-lg-9 col-xl-7">
          <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
            <div class="card-body p-4 p-md-5">
              <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Registration Form</h3>
              <form method= "post" enctype="multipart/form-data">
                {% csrf_token %}
  
                <div class="row">
                  <div class="col-md-6 mb-4">
  
                    <div class="form-outline">
                      <input type="text" id="firstName" class="form-control form-control-lg" name="first_name"/>
                      <label class="form-label" for="firstName">First Name</label>
                    </div>
  
                  </div>
                  <div class="col-md-6 mb-4">
  
                    <div class="form-outline">
                      <input type="text" id="lastName" class="form-control form-control-lg" name="last_name"/>
                      <label class="form-label" for="lastName">Last Name</label>
                    </div>
  
                  </div>
                </div>
  
                <div class="row">
                  <div class="col-md-6 mb-4 d-flex align-items-center">
  
                    <div class="form-outline datepicker w-100">
                      <input type="text" class="form-control form-control-lg" name = "age" />
                      <label class="form-label">Your age</label>
                    </div>
  
                  </div>
                  <div class="col-md-6 mb-4">
  
                    <h6 class="mb-2 pb-1">Gender: </h6>
  
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="gender" id="femaleGender"
                        value="option1" checked />
                      <label class="form-check-label" for="femaleGender">Female</label>
                    </div>
  
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="gender"
                        value="option2" />
                      <label class="form-check-label" for="maleGender">Male</label>
                    </div>
  
                  </div>


                  </div>
                </div>
  
                <div class="row">
                  <div class="col-md-6 mb-4 pb-2">
  
                    <div class="form-outline">
                      <input type="email" id="emailAddress" class="form-control form-control-lg" name ="email" />
                      <label class="form-label" for="emailAddress">Email</label>
                    </div>

                    <div class="form-group">
                      <label for="userpassword">Password</label>
                      <input type="password" class="form-control" placeholder="Password" name = "password">
                    </div>
  
                  </div>
                  <div class="col-md-6 mb-4 pb-2">
  
                    <div class="form-outline">
                      <input type="tel" id="phoneNumber" class="form-control form-control-lg" name="phoneNumber" />
                      <label class="form-label" for="phoneNumber">Phone Number</label>
                    </div>
  
                  </div>
                </div>
  
                <div class="row">
                  <div class="col-12">
  
                    <select class="select form-control-lg" name = "city">
                      <option value="1" disabled>Choose option</option>
                      <option value="Riyadh">Riyadh</option>
                      <option value="Jeddah">Jeddah</option>
                      <option value="Dammam">Dammam</option>
                      <option value="Medina">Medina</option>
                    </select>
                    <label class="form-label select-label">City</label>
  
                  </div>
                </div>

                <div class="row">
                    <div class="col-12">
    
                      <select class="select form-control-lg" name = "is_skater" >
                        <option value="1" disabled>Choose option</option>
                        <option value="True">Yes</option>
                        <option value="False">No</option>
                        
                      </select>
                      <label class="form-label select-label">Are you Skater?</label>
    
                    </div>
                  </div>
                  <label  class="form-label mt-3">Profile Image</label>
                  <input type="file" name="avatar" accept="image/*" class="form-control" />
  
                <div class="mt-4 pt-2">
                  <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
                </div>
                <p class="mb-5 pb-lg-2 mt-5 p-3" style="color: #393f81;">You have already an account? <a href="{% url 'accounts:login' %}"
                    style="color: #393f81;">Login here</a></p>
  
              </form>
            </div> 
          </div>
        </div>
      </div>
    </div>
  </section>



  {% endblock %}

Medsk8/learnSkateboard/templates/learnSkateboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!--Head-->
 <head>
    <meta charset= "UTF-8">
    <meta http-equiv= "X-UA-Compatible" content= "IE=edge">
    <meta name= "viewport" content= "width-device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>{% block title %}MEDSK8{% endblock %}</title>
    
 </head>
 <body class = bg-secondary>
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <div class="navbar navbar-expand-md bg-dark navbar-dark text-white">
        <div class="container">
            <a href="{% url 'skateboardBlog:home' %}" class= "navbar-brand">MEDSK8</a>
            <button
                class= "navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#mainmenu"
            >
            <span class= "navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="mainmenu">
                <ul class= "navbar-nav ms-auto">
                    <li class= "nav-item"><a href="{% url 'learnSkateboard:home' %}" class="nav-link">Home</a></li>
                    <li class= "nav-item"><a href="{% url 'learnSkateboard:components' %}" class= "nav-link">Compontents</a></li>
                    <li class= "nav-item"><a href="{% url 'learnSkateboard:home' %}" class="nav-link">LearnSkateboarding</a></li>
                </ul>
            </div>
        </div>
    </div>
    

    <!--Content-->
    

<!-- -Content- -->
<div class="mainContent">
    </article>
  </section>
  
  <section id= "hero" class= "bg-dark text-light text-center text-sm-start ру-5">
    <div class= "container">
        <div class="d-sm-flex align-items-center justify-content-center">
            <div class= "ру-3">
                {% block header %}
                <h1 class= "display-5"> مرحبا بك في ميدسكيت <span class="text-info">من نحن ؟ </span></h1>
                <p class= "ру-1 lead" >مجموعة لاعبين من مختلف الأماكن تجمعنا رياضة التزلج على اللوح</p>
                <a href="{% url 'skateboardBlog:home' %}"><button class= "btn btn-info">ابدا الان</button></a>
                {% endblock %}
            </div>
            <img class= "d-none d-sm-block img-fluid w-50" Src="{% static 'images/logo.svg' %}">
            
        </div>
    </div>
    </section>
    {% block content %}{% endblock  %}
  

        <!--          Cards             -->
                    {%block Card %}
                    <section class="py-5">
                      <div class="container">
                          <div class="row text-center">
                  
                              <div class="col-sm">
                                  <div class="card bg-dark text-light mb-3">
                                      <div class="h1 mt-3">
                                          <i class= "bi bi-award-fill"></i>
                                      </div>
                                      <div class="card-body text-center mt-3">
                                          <h4 class="card-title">Experince</h4>
                                          <p class= "card-text" >We have many projects before this website Here is our last Projects & Experince </p>
                                          <a href="https://twitter.com/tuwaiqacademy" class= "btn btn-info">Learn More</a>
                                      </div>
                                  </div>
                              </div>
                  
                              <div class="col-sm">
                                <div class="card bg-dark text-light mb-3">
                                    <div class="h1 mt-3">
                                      <i class="bi bi-list-nested"></i>
                                    </div>
                                    <div class="card-body text-center mt-3">
                                        <h4 class="card-title">Learn Skateboarding</h4>
                                        <p class= "card-text" >Skateboarding is so Funny. We offer Skateboarding courses you can chick it out from here</p>
                                        <a href="" class= "btn btn-info">Start Learning</a>
                                    </div>
                                </div>
                            </div>
                  
                              <div class="col-sm">
                                  <div class="card bg-dark text-light mb-3">
                                      <div class="h1 mt-3">
                                          <i class= "bi bi-person-lines-fill"></i>
                                      </div>
                                      <div class="card-body text-center mt-3">
                                          <h4 class="card-title">Contact us</h4>
                                          <p class= "card-text" >We are free For any questions. Working time: from 8am till 4pm </p>
                                          <a href="{% url 'skateboardBlog:home' %}" class= "btn btn-info">Learn More</a>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </section>
                    {% endblock %}

            

                   
                    <!-- Footer -->
<footer class="bg-dark text-center text-white">
    <!-- Grid container -->
    <div class="container p-4">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Whatsapp -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="bi bi-whatsapp"></i></a>
  
        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="bi bi-twitter"></i></a>
  
        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="bi bi-instagram"></i>
        </a>
  
        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/M-I4" role="button"
          ><i class="bi bi-github"></i></a>
      </section>
      <!-- Section: Social media -->
  
      <!-- Section: Form -->
      <section class="">
        <form action="">
          <!--Grid row-->
          <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-auto">
              <p class="pt-2">
                <strong>Search</strong>
              </p>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-md-5 col-12">
              <!-- Email input -->
              <div class="form-outline form-white mb-4">
                <input type="text" class="form-control" />
                <label class="form-label" for="form5Example21">LearnSkateboarding</label>
              </div>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-auto">
              <!-- Submit button -->
              <button type="submit" class="btn btn-outline-light mb-4">
                Enter
              </button>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </form>
      </section>
      <!-- Section: Form -->
  
      <!-- Section: Text -->
      <section class="mb-4">
        <span class="text-info">MEDSK8</span></h1>
        <p>
            مجموعة لاعبين من مختلف الأماكن تجمعنا رياضة التزلج على اللوح
        </p>
      </section>
      <!-- Section: Text -->
  
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Blog</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#!" class="text-white">Posts</a>
              </li>
              <li>
                <a href="#!" class="text-white">Add post</a>
              </li>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Learn Skateboarding</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#!" class="text-white">Home</a>
              </li>
              <li>
                <a href="#!" class="text-white">Components</a>
              </li>
              <li>
                <a href="#!" class="text-white">Types</a>
              </li>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Contact us</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#!" class="text-white">Instagram</a>
              </li>
              <li>
                <a href="#!" class="text-white">Twitter</a>
              </li>
              <li>
                <a href="#!" class="text-white">Github</a>
              </li>
              <li>
                <a href="#!" class="text-white">Email</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2022 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/">MEDSK8.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
    

    
</body>
</html>

Medsk8/learnSkateboard/templates/learnSkateboard/components.html
{% extends 'learnSkateboard/base.html' %}
{% load static %}


{% block title %}Components{% endblock  %}

{% block header %}
                <h1 class= "display-5">مكونات<span class="text-info"> لوح التزلج </span></h1>
                <p class= "ру-1 lead" >	يتشترك معظم ألواح التزلج في مكونات وأجزاء عامة وتوجد العديد من الأشكال الغريبة والتصاميم التي تقع خارج نطاق بعض الأوصاف المشتركة، أما الأجزاء المعتادة لتصميم لوح التزلج تتكون من التالي
                </p>
                
{% endblock %}




{% block content %}

<br>
<br>
  <section id= "hero" class= "bg-dark text-light text-center text-sm-start ру-5">
    <div class= "container">
        <div class="d-sm-flex align-items-center justify-content-center">
            <div class= "ру-3">
                
                <h1 class= "display-5"><span class="text-info">اللوح</span></h1>
                <p class= "ру-1 lead" >	مصنوع من مواد خاصة تساعد على الحفاظ على سطح اللوح من الكسر : مثل الألياف الزجاجية، الخيزران، الراتنج وألياف الكربون والألمنيوم، واللدائن والخشب والقيقب ,تختلف في الحجم واللون والجودة، ويصل طول معظمها من 7 حتى 10,5 بوصة، ويمكن استخدام ألواح أوسع للمزيد من الاستقرار عند القفز أو الانحدار من منحدر التزلج وفي هذه الحالة يجب أن يكون طولها بين 28 و 33 بوصة، أحيانا يتم طباعة اسم الشركة المصنعة في أسفل اللوح.
                </p>
                
                
            </div>
            <img class= "d-none d-sm-block img-fluid w-50" Src="{% static 'images/undraw_skateboard.svg' %}">
            
        </div>
    </div>
    </section>
<br>
<br>

    <section id= "hero" class= "bg-dark text-light text-center text-sm-start ру-5">
        <div class= "container">
            <div class="d-sm-flex align-items-center justify-content-center">
                <div class= "ру-3">
                    
                    <h1 class= "display-5"><span class="text-info">الحاملات</span></h1>
                    <p class= "ру-1 lead" >	يتكون لوح التزلج أيضاً من حاملات معدنية غالبا تكون أثنين مصنوعة من سبائك الألومنيوم، وهي التي تصل العجلات مع اللوح وتتكون الحاملات من جزأين مرتبطين الجزء العلوي يربط الحاملة مع اللوح ويسمى الأساس، وتحتها حلقات من المطاط توفر سهولة آلية التحويل والانتقال والتحكم باللوح. والجزء السفلي يرتبط بالعجلات.ويمكن من خلال شد أو تخفيف المسمار إيجاد أفضل طريقة للتحكم باللوح والاستقرار أثناء تنفيذ الحركات.
                    </p>
                    
                </div>
                <img class= "d-none d-sm-block img-fluid w-50" Src="{% static 'images/trucks.svg' %}">
                
            </div>
        </div>
        </section>

<br>
<br>


        <section id= "hero" class= "bg-dark text-light text-center text-sm-start ру-5">
            <div class= "container">
                <div class="d-sm-flex align-items-center justify-content-center">
                    <div class= "ру-3">
                        
                        <h1 class= "display-5"> مرحبا بك في ميدسكيت <span class="text-info">من نحن ؟ </span></h1>
                        <p class= "ру-1 lead" >مجموعة لاعبين من مختلف الأماكن تجمعنا رياضة التزلج على اللوح</p>
                        <a href="{% url 'skateboardBlog:home' %}"><button class= "btn btn-info">ابدا الان</button></a>
                        
                    </div>
                    <img class= "d-none d-sm-block img-fluid w-50" Src="{% static 'images/logo.svg' %}">
                    
                </div>
            </div>
            </section>
            <br><br>
    {% endblock  %}

Medsk8/skateboardBlog/templates/skateboardBlog/add_post.html
{% extends 'skateboardBlog/base.html' %}

{% block title %} Add New Post {% endblock %}

{% block header %}
    <h1>Add New <span class="text-info">Post</span></h1>
{% endblock %}
{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label  class="form-label">Title</label>
            <input type="text" class="form-control" name="title">
        </div>

        <label  class="form-label">Post Image</label>
        <input type="file" name="image" accept="image/*" class="form-control" />

        <div class="mb-3">
            <label  class="form-label">Content</label>
            <textarea type="text" class="form-control" name="content"></textarea>
        </div>

        <div class="mb-3">
            <label class="form-label">Publish Date</label>
            <input type="datetime-local" class="form-control" name="publish_date" />
        </div>


        <div class="mb-3">
            <label class="form-lable">Post Type:</label>
            <select class="form-control" name="post_type">
                {% for choice in Post.post_type_choices.choices %}
                <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>
        
        <input class="btn btn-primary" type="submit" value="Creat Post" />
    </form>
{% endblock %}